[package]
name = "client-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "asfaload-cli"
path = "src/main.rs"

[dependencies]
anstream = "0.6"
anstyle = "1"
clap = { version = "4.5.53", features = ["derive", "env"] }
thiserror = "2.0"
anyhow = "1.0"
rpassword = "7.4.0"
features_lib = { path = "../core/features_lib/" }
zxcvbn = "3.1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
admin-lib = { path = "../admin-lib" }
signatures = { version = "0.1.0", path = "../core/signatures" }
common = { path = "../core/common/" }
signers_file_types = { path = "../core/signers_file_types" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs"] }
rest_api_types = { path = "../rest_api_types" }
sha2 = "0.11"
hex = "0.4"
client-lib = { path = "../client-lib" }
forge-url = { path = "../file-auth/forge-url" }
url = "2.5"
shell-words = "1.1.1"
inquire = "0.9.4"
bishop = "1.0.0"
colored = "3"

[dev-dependencies]
mockito = "1.2"
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3.14"
test_helpers = { path = "../core/test_helpers" }
base64 = "0.22"

[lints]
workspace = true
